service:
  name: gateway-service

server:
  port: 8060

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      routes:
        - id: forms-service
          uri: http://forms:8080
          predicates:
            - Path=/forms/**
          filters:
            - RewritePath=/forms/(?<path>.*), /$\{path}
        - id: tariffcalculator-service
          uri: http://tariffcalculator:8080
          predicates:
            - Path=/tariffcalculator/**
          filters:
            - RewritePath=/tariffcalculator/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: forms-service
        url: /v3/api-docs/forms
      - name: tariff-service
        url: /v3/api-docs/tariffcalculator
